openapi: 3.1.0
info:
  title: Simple Hello World API
  version: 1.0.0
paths:
  /hello:
    get:
      summary: Get a Hello World message
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
                example: Hello, World!
